// Copyright (c) The University of Edinburgh, 2008.
//
// LICENCE-START
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software 
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// LICENCE-END


package uk.org.ogsadai.activity.block;

import java.util.Random;

/**
 * A random split generator.
 * 
 * @author The OGSA-DAI Project Team.
 */
public class RandomSplit implements Split
{
    /** Copyright statement */
    private static final String COPYRIGHT_NOTICE = 
        "Copyright (c) The University of Edinburgh, 2008";

    /** Random generator */
    private Random mRandom;

    /** Maximum value generated by this split is <code>mCount-1</code> */
    private int mCount;

    /**
     * Constructs a new random split generator.
     * 
     * @param seed
     *            random seed
     */
    public RandomSplit(Long seed) 
    {
        if (seed == null)
        {
            mRandom = new Random();
        }
        else
        {
            mRandom = new Random(seed.longValue());
        }
    }

    // Interface implementation
    public int next()
    {
        return mRandom.nextInt(mCount);
    }

    // Interface implementation
    public void setSize(int n)
    {
        mCount = n;
    }

}
