
FROM fedora:20
MAINTAINER Dave Morris <docker-admin@metagrid.co.uk>

#
# Install some tools
RUN yum -y install wget
RUN yum -y install unzip
RUN yum -y install pwgen
RUN yum -y install deltarpm

#
# Update the system
RUN yum -y update

