FROM firethorn/ubuntu:2.1.33-stv-tap-swarm
MAINTAINER Stelios Voutsinas <stv@roe.ac.uk>

#
# Install Python

RUN apt-get install -y g++
RUN apt-get install -y unixodbc unixodbc-dev freetds-dev tdsodbc python-dev libmyodbc
RUN apt-get install -y python python-dev python-distribute python-pip

