'''
config module

Created on Nov 30, 2011
Configuration and Properties Variables for the FreeForm SQL processing page

@author: stelios
'''
import web
import os
import logging

from config import (use_config, mode_global, request, result_format, lang, cur_static_dir,
survey_sub_path, registry_url, tap_factory,  survey_cgi_bin, MAX_FILE_SIZE,delay, 
getImageURL, use_cached_endpoints, SURVEY_TAP_TITLE, SURVEY_TAP,survey_prefix, publicly_visible_temp_dir, host_temp_directory,
firethorn_base, userhomedir, SURVEY_DB)



ERROR_HTML = "<div style=\"color:red;margin-left:50px;\">No elements returned. Please check your query</div>"
survey_endpoint_tr =  '<tr><th><label for="' + SURVEY_TAP_TITLE + '_' + SURVEY_TAP + '">' + SURVEY_TAP_TITLE + '</label></th><td><input type="checkbox" name="' + SURVEY_TAP_TITLE + '" value="' + SURVEY_TAP + '" id="' + SURVEY_TAP_TITLE + '_' + SURVEY_TAP + '" checked="checked"></td></tr>'
add_catalogue_html = '<a title="remove this catalogue" class="ui-icon delete fl">Delete catalogue</a>'
remove_catalogue_html =  '<a title="add this catalogue" class="ui-icon add fl">Add catalogue</a>'
starting_catalogue_id = ""
atlasworkspace = ""
atlasschema = ""
selected_cached_endpoints = ""
unselected_cached_endpoints = ""

   
cached_endpoints_voexplorer = """
  <tbody><tr><th><label for="august onboard Phobos2, atmospheric composition of mars_http://voparis-tap.obspm.fr/__system__/tap/run/tap">august onboard Phobos2, atmospheric composition of mars</label></th><td><input type="checkbox" name="august onboard Phobos2, atmospheric composition of mars" value="http://voparis-tap.obspm.fr/__system__/tap/run/tap" id="august onboard Phobos2, atmospheric composition of mars_http://voparis-tap.obspm.fr/__system__/tap/run/tap"></td></tr>
    <tr><th><label for="GAVO data center TAP service_http://dc.zah.uni-heidelberg.de/__system__/tap/run/tap">GAVO data center TAP service</label></th><td><input type="checkbox" name="GAVO data center TAP service" value="http://dc.zah.uni-heidelberg.de/__system__/tap/run/tap" id="GAVO data center TAP service_http://dc.zah.uni-heidelberg.de/__system__/tap/run/tap"></td></tr>
    <tr><th><label for="VVV DR1 - VISTA Variables in the Via Lactea survey_http://wfaudata.roe.ac.uk/vvvDR1-dsa/TAP">VVV DR1 - VISTA Variables in the Via Lactea survey</label></th><td><input type="checkbox" name="VVV DR1 - VISTA Variables in the Via Lactea survey" value="http://wfaudata.roe.ac.uk/vvvDR1-dsa/TAP" id="VVV DR1 - VISTA Variables in the Via Lactea survey_http://wfaudata.roe.ac.uk/vvvDR1-dsa/TAP"></td></tr>
    <tr><th><label for="VMC DR1 - VISTA Magellanic System survey_http://wfaudata.roe.ac.uk/vmcDR1-dsa/TAP">VMC DR1 - VISTA Magellanic System survey</label></th><td><input type="checkbox" name="VMC DR1 - VISTA Magellanic System survey" value="http://wfaudata.roe.ac.uk/vmcDR1-dsa/TAP" id="VMC DR1 - VISTA Magellanic System survey_http://wfaudata.roe.ac.uk/vmcDR1-dsa/TAP"></td></tr>
    <tr><th><label for="VIKING - VISTA Kilo-degree Infrared Galaxy survey Data Release 2_http://wfaudata.roe.ac.uk/vikingDR2-dsa/TAP">VIKING - VISTA Kilo-degree Infrared Galaxy survey Data Release 2</label></th><td><input type="checkbox" name="VIKING - VISTA Kilo-degree Infrared Galaxy survey Data Release 2" value="http://wfaudata.roe.ac.uk/vikingDR2-dsa/TAP" id="VIKING - VISTA Kilo-degree Infrared Galaxy survey Data Release 2_http://wfaudata.roe.ac.uk/vikingDR2-dsa/TAP"></td></tr>
    <tr><th><label for="VIDEO DR2 - VISTA Deep Extragalactic Observations survey_http://wfaudata.roe.ac.uk/videoDR2-dsa/TAP">VIDEO DR2 - VISTA Deep Extragalactic Observations survey</label></th><td><input type="checkbox" name="VIDEO DR2 - VISTA Deep Extragalactic Observations survey" value="http://wfaudata.roe.ac.uk/videoDR2-dsa/TAP" id="VIDEO DR2 - VISTA Deep Extragalactic Observations survey_http://wfaudata.roe.ac.uk/videoDR2-dsa/TAP"></td></tr>
    <tr><th><label for="auroral planetary imaging and spectroscopy_http://voparis-tap.obspm.fr/__system__/tap/run/tap">auroral planetary imaging and spectroscopy</label></th><td><input type="checkbox" name="auroral planetary imaging and spectroscopy" value="http://voparis-tap.obspm.fr/__system__/tap/run/tap" id="auroral planetary imaging and spectroscopy_http://voparis-tap.obspm.fr/__system__/tap/run/tap"></td></tr>
    <tr><th><label for="Temperature vertical profiles in the Titan middle atmosphere_http://voparis-tap.obspm.fr/__system__/tap/run/tap">Temperature vertical profiles in the Titan middle atmosphere</label></th><td><input type="checkbox" name="Temperature vertical profiles in the Titan middle atmosphere" value="http://voparis-tap.obspm.fr/__system__/tap/run/tap" id="Temperature vertical profiles in the Titan middle atmosphere_http://voparis-tap.obspm.fr/__system__/tap/run/tap"></td></tr>
    <tr><th><label for="Base de Donnees d'Images Planetaires_http://voparis-tap.obspm.fr/__system__/tap/run/tap">Base de Donnees d'Images Planetaires</label></th><td><input type="checkbox" name="Base de Donnees d'Images Planetaires" value="http://voparis-tap.obspm.fr/__system__/tap/run/tap" id="Base de Donnees d'Images Planetaires_http://voparis-tap.obspm.fr/__system__/tap/run/tap"></td></tr>
    <tr><th><label for="The Nancay Cometary Database_http://voparis-srv.obspm.fr/srv/tap-basecom">The Nancay Cometary Database</label></th><td><input type="checkbox" name="The Nancay Cometary Database" value="http://voparis-srv.obspm.fr/srv/tap-basecom" id="The Nancay Cometary Database_http://voparis-srv.obspm.fr/srv/tap-basecom"></td></tr>
    <tr><th><label for="Abundance vertical profiles in the Titan middle atmosphere_http://voparis-srv.obspm.fr/srv/tap-titan_abundance">Abundance vertical profiles in the Titan middle atmosphere</label></th><td><input type="checkbox" name="Abundance vertical profiles in the Titan middle atmosphere" value="http://voparis-srv.obspm.fr/srv/tap-titan_abundance" id="Abundance vertical profiles in the Titan middle atmosphere_http://voparis-srv.obspm.fr/srv/tap-titan_abundance"></td></tr>
    <tr><th><label for="Temperature vertical profiles in the Titan middle atmosphere_http://voparis-srv.obspm.fr/srv/tap-titan_temperature">Temperature vertical profiles in the Titan middle atmosphere</label></th><td><input type="checkbox" name="Temperature vertical profiles in the Titan middle atmosphere" value="http://voparis-srv.obspm.fr/srv/tap-titan_temperature" id="Temperature vertical profiles in the Titan middle atmosphere_http://voparis-srv.obspm.fr/srv/tap-titan_temperature"></td></tr>
    <tr><th><label for="HEASARC Xamin Catalog Interface_http://heasarc.gsfc.nasa.gov/xamin/vo/tap">HEASARC Xamin Catalog Interface</label></th><td><input type="checkbox" name="HEASARC Xamin Catalog Interface" value="http://heasarc.gsfc.nasa.gov/xamin/vo/tap" id="HEASARC Xamin Catalog Interface_http://heasarc.gsfc.nasa.gov/xamin/vo/tap"></td></tr>
    <tr><th><label for="XMM-Newton Serendipitous Source Catalogue (2XMM)_http://wfaudata.roe.ac.uk/xmm-dsa/TAP">XMM-Newton Serendipitous Source Catalogue (2XMM)</label></th><td><input type="checkbox" name="XMM-Newton Serendipitous Source Catalogue (2XMM)" value="http://wfaudata.roe.ac.uk/xmm-dsa/TAP" id="XMM-Newton Serendipitous Source Catalogue (2XMM)_http://wfaudata.roe.ac.uk/xmm-dsa/TAP"></td></tr>
    <tr><th><label for="VHS DR1 - VISTA Hemisphere Survey Data Release 1_http://wfaudata.roe.ac.uk/vhsDR1-dsa/TAP">VHS DR1 - VISTA Hemisphere Survey Data Release 1</label></th><td><input type="checkbox" name="VHS DR1 - VISTA Hemisphere Survey Data Release 1" value="http://wfaudata.roe.ac.uk/vhsDR1-dsa/TAP" id="VHS DR1 - VISTA Hemisphere Survey Data Release 1_http://wfaudata.roe.ac.uk/vhsDR1-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR2 World Release_http://wfaudata.roe.ac.uk/ukidssWorld-dsa/TAP">UKIDSS DR2 World Release</label></th><td><input type="checkbox" name="UKIDSS DR2 World Release" value="http://wfaudata.roe.ac.uk/ukidssWorld-dsa/TAP" id="UKIDSS DR2 World Release_http://wfaudata.roe.ac.uk/ukidssWorld-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR8 - UKIRT Infrared Deep Sky Survey Data Release 8_http://wfaudata.roe.ac.uk/ukidssDR8-dsa/TAP">UKIDSS DR8 - UKIRT Infrared Deep Sky Survey Data Release 8</label></th><td><input type="checkbox" name="UKIDSS DR8 - UKIRT Infrared Deep Sky Survey Data Release 8" value="http://wfaudata.roe.ac.uk/ukidssDR8-dsa/TAP" id="UKIDSS DR8 - UKIRT Infrared Deep Sky Survey Data Release 8_http://wfaudata.roe.ac.uk/ukidssDR8-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR7 - UKIRT Infrared Deep Sky Survey Data Release 7_http://wfaudata.roe.ac.uk/ukidssDR7-dsa/TAP">UKIDSS DR7 - UKIRT Infrared Deep Sky Survey Data Release 7</label></th><td><input type="checkbox" name="UKIDSS DR7 - UKIRT Infrared Deep Sky Survey Data Release 7" value="http://wfaudata.roe.ac.uk/ukidssDR7-dsa/TAP" id="UKIDSS DR7 - UKIRT Infrared Deep Sky Survey Data Release 7_http://wfaudata.roe.ac.uk/ukidssDR7-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR6 - UKIRT Infrared Deep Sky Survey Data Release 6_http://wfaudata.roe.ac.uk/ukidssDR6-dsa/TAP">UKIDSS DR6 - UKIRT Infrared Deep Sky Survey Data Release 6</label></th><td><input type="checkbox" name="UKIDSS DR6 - UKIRT Infrared Deep Sky Survey Data Release 6" value="http://wfaudata.roe.ac.uk/ukidssDR6-dsa/TAP" id="UKIDSS DR6 - UKIRT Infrared Deep Sky Survey Data Release 6_http://wfaudata.roe.ac.uk/ukidssDR6-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR5 - UKIRT Infrared Deep Sky Survey Data Release 5_http://wfaudata.roe.ac.uk/ukidssDR5-dsa/TAP">UKIDSS DR5 - UKIRT Infrared Deep Sky Survey Data Release 5</label></th><td><input type="checkbox" name="UKIDSS DR5 - UKIRT Infrared Deep Sky Survey Data Release 5" value="http://wfaudata.roe.ac.uk/ukidssDR5-dsa/TAP" id="UKIDSS DR5 - UKIRT Infrared Deep Sky Survey Data Release 5_http://wfaudata.roe.ac.uk/ukidssDR5-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR4 - UKIRT Infrared Deep Sky Survey Data Release 4_http://wfaudata.roe.ac.uk/ukidssDR4-dsa/TAP">UKIDSS DR4 - UKIRT Infrared Deep Sky Survey Data Release 4</label></th><td><input type="checkbox" name="UKIDSS DR4 - UKIRT Infrared Deep Sky Survey Data Release 4" value="http://wfaudata.roe.ac.uk/ukidssDR4-dsa/TAP" id="UKIDSS DR4 - UKIRT Infrared Deep Sky Survey Data Release 4_http://wfaudata.roe.ac.uk/ukidssDR4-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR3 - UKIRT Infrared Deep Sky Survey Data Release 3_http://wfaudata.roe.ac.uk/ukidssDR3-dsa/TAP">UKIDSS DR3 - UKIRT Infrared Deep Sky Survey Data Release 3</label></th><td><input type="checkbox" name="UKIDSS DR3 - UKIRT Infrared Deep Sky Survey Data Release 3" value="http://wfaudata.roe.ac.uk/ukidssDR3-dsa/TAP" id="UKIDSS DR3 - UKIRT Infrared Deep Sky Survey Data Release 3_http://wfaudata.roe.ac.uk/ukidssDR3-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR2 - UKIRT Infrared Deep Sky Survey Data Release 2_http://wfaudata.roe.ac.uk/ukidssDR2-dsa/TAP">UKIDSS DR2 - UKIRT Infrared Deep Sky Survey Data Release 2</label></th><td><input type="checkbox" name="UKIDSS DR2 - UKIRT Infrared Deep Sky Survey Data Release 2" value="http://wfaudata.roe.ac.uk/ukidssDR2-dsa/TAP" id="UKIDSS DR2 - UKIRT Infrared Deep Sky Survey Data Release 2_http://wfaudata.roe.ac.uk/ukidssDR2-dsa/TAP"></td></tr>
    <tr><th><label for="UKIDSS DR1 - UKIRT Infrared Deep Sky Survey Data Release 1_http://wfaudata.roe.ac.uk/ukidssDR1-dsa/TAP">UKIDSS DR1 - UKIRT Infrared Deep Sky Survey Data Release 1</label></th><td><input type="checkbox" name="UKIDSS DR1 - UKIRT Infrared Deep Sky Survey Data Release 1" value="http://wfaudata.roe.ac.uk/ukidssDR1-dsa/TAP" id="UKIDSS DR1 - UKIRT Infrared Deep Sky Survey Data Release 1_http://wfaudata.roe.ac.uk/ukidssDR1-dsa/TAP"></td></tr>
    <tr><th><label for="Two Micron All Sky Survey (2MASS)_http://wfaudata.roe.ac.uk/twomass-dsa/TAP">Two Micron All Sky Survey (2MASS)</label></th><td><input type="checkbox" name="Two Micron All Sky Survey (2MASS)" value="http://wfaudata.roe.ac.uk/twomass-dsa/TAP" id="Two Micron All Sky Survey (2MASS)_http://wfaudata.roe.ac.uk/twomass-dsa/TAP"></td></tr>
    <tr><th><label for="SuperCOSMOS Science Archive (SSA)_http://wfaudata.roe.ac.uk/ssa-dsa/TAP">SuperCOSMOS Science Archive (SSA)</label></th><td><input type="checkbox" name="SuperCOSMOS Science Archive (SSA)" value="http://wfaudata.roe.ac.uk/ssa-dsa/TAP" id="SuperCOSMOS Science Archive (SSA)_http://wfaudata.roe.ac.uk/ssa-dsa/TAP"></td></tr>
    <tr><th><label for="SDSS DR8 - Sloan Digital Sky Survey Data Release 8_http://wfaudata.roe.ac.uk/sdssdr8-dsa/TAP">SDSS DR8 - Sloan Digital Sky Survey Data Release 8</label></th><td><input type="checkbox" name="SDSS DR8 - Sloan Digital Sky Survey Data Release 8" value="http://wfaudata.roe.ac.uk/sdssdr8-dsa/TAP" id="SDSS DR8 - Sloan Digital Sky Survey Data Release 8_http://wfaudata.roe.ac.uk/sdssdr8-dsa/TAP"></td></tr>
    <tr><th><label for="SDSS DR7 - Sloan Digital Sky Survey Data Release 7_http://wfaudata.roe.ac.uk/sdssdr7-dsa/TAP">SDSS DR7 - Sloan Digital Sky Survey Data Release 7</label></th><td><input type="checkbox" name="SDSS DR7 - Sloan Digital Sky Survey Data Release 7" value="http://wfaudata.roe.ac.uk/sdssdr7-dsa/TAP" id="SDSS DR7 - Sloan Digital Sky Survey Data Release 7_http://wfaudata.roe.ac.uk/sdssdr7-dsa/TAP"></td></tr>
    <tr><th><label for="SDSS DR6 SEGUE - Sloan Digital Sky Survey Data Release 6_http://wfaudata.roe.ac.uk/sdssdr6-dsa/TAP">SDSS DR6 SEGUE - Sloan Digital Sky Survey Data Release 6</label></th><td><input type="checkbox" name="SDSS DR6 SEGUE - Sloan Digital Sky Survey Data Release 6" value="http://wfaudata.roe.ac.uk/sdssdr6-dsa/TAP" id="SDSS DR6 SEGUE - Sloan Digital Sky Survey Data Release 6_http://wfaudata.roe.ac.uk/sdssdr6-dsa/TAP"></td></tr>
    <tr><th><label for="SDSS DR5 - Sloan Digital Sky Survey Data Release 5_http://wfaudata.roe.ac.uk/sdssdr5-dsa/TAP">SDSS DR5 - Sloan Digital Sky Survey Data Release 5</label></th><td><input type="checkbox" name="SDSS DR5 - Sloan Digital Sky Survey Data Release 5" value="http://wfaudata.roe.ac.uk/sdssdr5-dsa/TAP" id="SDSS DR5 - Sloan Digital Sky Survey Data Release 5_http://wfaudata.roe.ac.uk/sdssdr5-dsa/TAP"></td></tr>
    <tr><th><label for="SDSS DR3 - Sloan Digital Sky Survey Data Release 3_http://wfaudata.roe.ac.uk/sdssdr3-dsa/TAP">SDSS DR3 - Sloan Digital Sky Survey Data Release 3</label></th><td><input type="checkbox" name="SDSS DR3 - Sloan Digital Sky Survey Data Release 3" value="http://wfaudata.roe.ac.uk/sdssdr3-dsa/TAP" id="SDSS DR3 - Sloan Digital Sky Survey Data Release 3_http://wfaudata.roe.ac.uk/sdssdr3-dsa/TAP"></td></tr>
    <tr><th><label for="Rontgen Satellite Archive (ROSAT)_http://wfaudata.roe.ac.uk/rosat-dsa/TAP">Rontgen Satellite Archive (ROSAT)</label></th><td><input type="checkbox" name="Rontgen Satellite Archive (ROSAT)" value="http://wfaudata.roe.ac.uk/rosat-dsa/TAP" id="Rontgen Satellite Archive (ROSAT)_http://wfaudata.roe.ac.uk/rosat-dsa/TAP"></td></tr>
    <tr><th><label for="Personal SuperCOSMOS Science Archive (SSA)_http://wfaudata.roe.ac.uk/pssa-dsa/TAP">Personal SuperCOSMOS Science Archive (SSA)</label></th><td><input type="checkbox" name="Personal SuperCOSMOS Science Archive (SSA)" value="http://wfaudata.roe.ac.uk/pssa-dsa/TAP" id="Personal SuperCOSMOS Science Archive (SSA)_http://wfaudata.roe.ac.uk/pssa-dsa/TAP"></td></tr>
    <tr><th><label for="Infrared Astronomical Satellite Archive (IRAS)_http://wfaudata.roe.ac.uk/iras-dsa/TAP">Infrared Astronomical Satellite Archive (IRAS)</label></th><td><input type="checkbox" name="Infrared Astronomical Satellite Archive (IRAS)" value="http://wfaudata.roe.ac.uk/iras-dsa/TAP" id="Infrared Astronomical Satellite Archive (IRAS)_http://wfaudata.roe.ac.uk/iras-dsa/TAP"></td></tr>
    <tr><th><label for="GLIMPSE (Galactic Legacy Infrared Mid-Plane Survey Extraordinaire)_http://wfaudata.roe.ac.uk/glimpse-dsa/TAP">GLIMPSE (Galactic Legacy Infrared Mid-Plane Survey Extraordinaire)</label></th><td><input type="checkbox" name="GLIMPSE (Galactic Legacy Infrared Mid-Plane Survey Extraordinaire)" value="http://wfaudata.roe.ac.uk/glimpse-dsa/TAP" id="GLIMPSE (Galactic Legacy Infrared Mid-Plane Survey Extraordinaire)_http://wfaudata.roe.ac.uk/glimpse-dsa/TAP"></td></tr>
    <tr><th><label for="FIRST Survey Catalogue (03Apr11 Version)_http://wfaudata.roe.ac.uk/first-dsa/TAP">FIRST Survey Catalogue (03Apr11 Version)</label></th><td><input type="checkbox" name="FIRST Survey Catalogue (03Apr11 Version)" value="http://wfaudata.roe.ac.uk/first-dsa/TAP" id="FIRST Survey Catalogue (03Apr11 Version)_http://wfaudata.roe.ac.uk/first-dsa/TAP"></td></tr>
    <tr><th><label for="AstroDAbis Notation Service_http://astrodabis.roe.ac.uk/astrodabis-dsa/TAP">AstroDAbis Notation Service</label></th><td><input type="checkbox" name="AstroDAbis Notation Service" value="http://astrodabis.roe.ac.uk/astrodabis-dsa/TAP" id="AstroDAbis Notation Service_http://astrodabis.roe.ac.uk/astrodabis-dsa/TAP"></td></tr>
    <tr><th><label for="6dF Galaxy Survey Data Release 3_http://wfaudata.roe.ac.uk/6dfdr3-dsa/TAP">6dF Galaxy Survey Data Release 3</label></th><td><input type="checkbox" name="6dF Galaxy Survey Data Release 3" value="http://wfaudata.roe.ac.uk/6dfdr3-dsa/TAP" id="6dF Galaxy Survey Data Release 3_http://wfaudata.roe.ac.uk/6dfdr3-dsa/TAP"></td></tr>
    <tr><th><label for="6dF Galaxy Survey Data Release 2_http://wfaudata.roe.ac.uk/6df-dsa/TAP">6dF Galaxy Survey Data Release 2</label></th><td><input type="checkbox" name="6dF Galaxy Survey Data Release 2" value="http://wfaudata.roe.ac.uk/6df-dsa/TAP" id="6dF Galaxy Survey Data Release 2_http://wfaudata.roe.ac.uk/6df-dsa/TAP"></td></tr>
</tbody>
"""


  
region_query_180_to_1 = """
          Query: 180 - 1
            <br /><br /><br /><br />
            SELECT  sourceID, framesetID, RA, Dec, mergedClass, priOrSec, YAperMag3,
YAperMag3Err, J_1AperMag3, J_1AperMag3Err, J_2AperMag3, J_2AperMag3Err,
HAperMag3, HAperMag3Err, KAperMag3,
KAperMag3Err,2*DEGREES(ASIN(sqrt(power(-0.9998476951563913-cx,2)+power(1.2244602795081332E-16-cy,2)+power(0.01745240643728351-cz,2))/2))*60
as distance  FROM lasSource WHERE dec > 0.9833333333333333 and dec <
1.0166666666666668 and RA >= 179.98333070918963 and RA <=
180.01666929081037 and ((cx * -0.9998476951563913 + cy *
1.2244602795081332E-16 + cz * 0.01745240643728351 ) >= 0.9999999576920253)"""
